# Generated by Django 4.1.5 on 2023-02-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.person'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='color',
            field=models.CharField(choices=[('w', 'White'), ('u', 'Blue'), ('b', 'Black'), ('r', 'Red'), ('g', 'Green'), ('colorless', 'Colorless'), ('wu', 'Azorius'), ('ub', 'Dimir'), ('br', 'Rakdos'), ('rg', 'Gruul'), ('gw', 'Selesnya'), ('wb', 'Orzhov'), ('ur', 'Izzet'), ('bg', 'Golgari'), ('rw', 'Boros'), ('gu', 'Simic'), ('wub', 'Esper'), ('ubr', 'Grixis'), ('brg', 'Jund'), ('rgw', 'Naya'), ('gwu', 'Bant'), ('wbg', 'Abzan'), ('urw', 'Jeskai'), ('bgu', 'Sultai'), ('rwb', 'Mardu'), ('gur', 'Temur'), ('wubr', 'Yore-Tiller'), ('ubrg', 'Glint-Eye'), ('brgw', 'Dune-Brood'), ('rgwu', 'Ink-Treader'), ('gwub', 'Witch-Maw'), ('wubrg', 'Five Color')], max_length=16),
        ),
    ]
